[[XML2]]
arch = "x86_64"
git-tree-sha1 = "01f46742f6c911ae380ae1e52be68ae9e4aefab2"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "84def34f6b079cb7ec89e60835571af1fa69955e01a563fc3bc5249ef967e325"
    url = "https://github.com/staticfloat/XML2_jll.jl/releases/download/v2.13.2-ClangBootstrap/XML2-v2.13.2-x86_64-linux-gnu.tar.gz"
[[XML2]]
arch = "aarch64"
git-tree-sha1 = "a04b4572aa8837d8ea7f403839808236e1107edf"
libc = "glibc"
os = "linux"

    [[XML2.download]]
    sha256 = "9f651ee6ada18fc3bc1367c4d51a1986298149a0256947d314d6f1cda4163b59"
    url = "https://github.com/staticfloat/XML2_jll.jl/releases/download/v2.13.2-ClangBootstrap/XML2-v2.13.2-aarch64-linux-gnu.tar.gz"

[[XML2-build_log]]
arch = "x86_64"
git-tree-sha1 = "d85a6fe26ed5f0fb7dd5df45aec1219db360f213"
lazy = true
libc = "glibc"
os = "linux"

    [[XML2-build_log.download]]
    sha256 = "27f44f7d06ea78d88f70f405d89475c3292ef720b0a193261a9711d256828ef3"
    url = "https://github.com/staticfloat/XML2_jll.jl/releases/download/v2.13.2-ClangBootstrap/XML2-build_log-v2.13.2-x86_64-linux-gnu.tar.gz"
[[XML2-build_log]]
arch = "aarch64"
git-tree-sha1 = "98d4a849a606d01abe6340325009da0d769b7b95"
lazy = true
libc = "glibc"
os = "linux"

    [[XML2-build_log.download]]
    sha256 = "a91f3cf0ab6de7f89b53944cb22bb04cb111230044e2b860d66439ee47200923"
    url = "https://github.com/staticfloat/XML2_jll.jl/releases/download/v2.13.2-ClangBootstrap/XML2-build_log-v2.13.2-aarch64-linux-gnu.tar.gz"

[[XML2-extract_log]]
arch = "x86_64"
git-tree-sha1 = "48b8f0e21573ed09e92418318926822713cdc993"
lazy = true
libc = "glibc"
os = "linux"

    [[XML2-extract_log.download]]
    sha256 = "edb7073966e20e5c0b512ac4c3601516259f5465dc5a70e1e79a2109fb8560cf"
    url = "https://github.com/staticfloat/XML2_jll.jl/releases/download/v2.13.2-ClangBootstrap/XML2-extract_log-v2.13.2-x86_64-linux-gnu.tar.gz"
[[XML2-extract_log]]
arch = "aarch64"
git-tree-sha1 = "8fee0e5ad49c0198c5bcb4346a8f72f6735b4fc1"
lazy = true
libc = "glibc"
os = "linux"

    [[XML2-extract_log.download]]
    sha256 = "bf7bfee674a2708f395c99253a0932017c80028ed3e22ad6a96b2aa6f388ba59"
    url = "https://github.com/staticfloat/XML2_jll.jl/releases/download/v2.13.2-ClangBootstrap/XML2-extract_log-v2.13.2-aarch64-linux-gnu.tar.gz"
